// Generated by CoffeeScript 1.9.3
(function() {
  window.galleryWindow = (function() {
    galleryWindow.prototype.positionId = 0;

    galleryWindow.prototype.maxChooseImg = 3;

    function galleryWindow(positionId) {
      var self;
      if (positionId == null) {
        positionId = 0;
      }
      this.positionId = positionId;
      self = this;
      new sendAjax('getGalleryContent', {
        id: this.positionId
      }, function(response) {
        self.setData(response.data);
        self.init();
        return self.initUploadify();
      });
    }

    galleryWindow.prototype.init = function() {
      var self;
      self = this;
      return this.windowGallery = new modalWindow({
        html: this.getContent(this.positionId),
        width: 1100,
        maxHeight: '100%',
        maxWidth: '90%',
        title: 'Галлерея изображений (выбор изображений для позиции)',
        buttons: [
          {
            text: 'Загрузить',
            "class": 'button_yes_or_no',
            id: self.data.token,
            click: function() {
              return self.destroy();
            }
          }, {
            text: 'Сохранить',
            "class": 'button_yes_or_no no',
            click: function() {
              return self.destroy();
            }
          }
        ]
      }, {
        closeOnEscape: true,
        single: true,
        close: function(event, ui) {
          return true;
        }
      });
    };

    galleryWindow.prototype.setData = function(data) {
      return this.data = data;
    };

    galleryWindow.prototype.getContent = function() {
      this.contentDiv = $('<div/>', {
        id: "rt-gallery-images"
      });
      this.contentDiv.append($('<ul/>'));
      return this.appendImgToGallery(this.data);
    };

    galleryWindow.prototype.appendImgToGallery = function(data) {
      var i, j, len, n, ref, ul;
      ul = this.contentDiv.find('ul');
      ref = data.images;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        n = ref[i];
        ul.append(this.getImage(n));
      }
      return this.contentDiv;
    };

    galleryWindow.prototype.initUploadify = function() {
      var self;
      self = this;
      this.contentDiv.append($('<div/>', {
        id: 'galleryWindowQueue'
      }));
      return $('#' + this.data.token).uploadify({
        'formData': {
          'AJAX': 'add_new_files_in_kp_gallery',
          'timestamp': this.data.timestamp,
          'token': this.data.token,
          'gnom': 'sdfdsfdsf',
          'id': this.data.id,
          'folder_name': this.data.folder_name
        },
        'simUploadLimit': 10,
        'buttonText': 'Загрузить',
        'width': 250,
        'swf': '../libs/php/uploadify.swf',
        'uploader': '',
        'multi': true,
        'queueID': 'galleryWindowQueue',
        'onUploadSuccess': function(file, data) {
          var response;
          response = jQuery.parseJSON(data);
          self.appendImgToGallery(response.data);
          self.scrollBottom();
          return standard_response_handler(response);
        }
      });
    };

    galleryWindow.prototype.getImage = function(imgData) {
      var img, li, self;
      img = $('<img/>', {
        src: imgData.img_link_global
      });
      li = $('<li/>', {
        "class": 'rt-gallery-cont',
        click: function() {
          return self.chooseImg($(this));
        }
      });
      self = this;
      if (imgData.img_folder !== 'img') {
        li.append($('<div/>', {
          "class": 'delete_upload_img',
          html: 'x',
          click: function() {
            event.preventDefault();
            event.stopPropagation();
            return self.deleteImg($(this));
          }
        }));
      }
      if (Number(imgData.checked) > 0) {
        li.addClass('checked');
      }
      return li.append(img);
    };

    galleryWindow.prototype.chooseImg = function(obj) {
      if (obj.hasClass('checked')) {
        return obj.removeClass('checked');
      } else {
        if (this.contentDiv.find('li.rt-gallery-cont.checked').length < 3) {
          return obj.addClass('checked');
        } else {
          return echo_message_js('В КП разрешено загружать не более ' + this.maxChooseImg + ' изображений', 'system_message', 2000);
        }
      }
    };

    galleryWindow.prototype.deleteImg = function(obj) {
      return obj.parent().hide(300, function() {
        $(this).remove();
        return echo_message_js('удалить изображение', 'successful_message', 100);
      });
    };

    galleryWindow.prototype.scrollBottom = function() {
      return this.contentDiv.stop().animate({
        "scrollTop": 99999
      }, "slow");
    };

    galleryWindow.prototype.destroy = function() {
      console.log(this.windowGallery);
      return $(this.windowGallery.winDiv[0]).dialog('close').dialog('destroy').remove();
    };

    return galleryWindow;

  })();

}).call(this);

//# sourceMappingURL=positionGallery.js.map
