// Generated by CoffeeScript 1.9.3
(function() {
  window.galleryWindow = (function() {
    function galleryWindow(positionId) {
      if (positionId == null) {
        positionId = 0;
      }
      this.init(positionId);
    }

    galleryWindow.prototype.init = function(positionId) {
      var self;
      self = this;
      return this.window = new modalWindow({
        html: this.getContent(positionId),
        maxHeight: '100%',
        maxWidth: '90%',
        title: 'Галлерея изображений (выбор изображений для позиции)',
        buttons: [
          {
            text: 'Загрузить',
            "class": 'button_yes_or_no',
            click: function() {
              return $(self.window.winDiv[0]).dialog('close').dialog('destroy').remove();
            }
          }, {
            text: 'Сохранить',
            "class": 'button_yes_or_no no',
            click: function() {
              return $(self.window.winDiv[0]).dialog('close').dialog('destroy').remove();
            }
          }
        ]
      }, {
        closeOnEscape: true,
        single: true,
        close: function(event, ui) {
          return true;
        }
      });
    };

    galleryWindow.prototype.getContent = function() {
      return $('<div/>', {
        html: "Картиночки =)"
      });
    };

    galleryWindow.prototype.destroy = function() {};

    return galleryWindow;

  })();

}).call(this);

//# sourceMappingURL=positionGallery.js.map
